{{- if .Values.ingress.enabled }}
{{- $existing := lookup "networking.k8s.io/v1" "IngressClass" .Values.ingress.className "" }}
{{- if not $existing }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className }}
spec:
  controller: {{ .Values.ingress.controller }}
{{- end }}
{{- end }}
