apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: "{{ .Values.persistence.size }}"
  volumeMode: Filesystem
  accessModes:
    - "{{ .Values.persistence.accessMode }}"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.efs.fileSystemId }}"
  mountOptions:
    - nfsvers=4.1  