apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - "{{ .Values.persistence.accessMode }}"
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  volumeName: efs-pv
  storageClassName: ""  
