apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: example
